# Generated by Django 4.2.1 on 2023-06-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_remove_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_Name', models.CharField(max_length=200)),
                ('bank_account', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.seller_company'),
        ),
    ]
