# Generated by Django 4.2.1 on 2023-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_rename_seller_company_product_seller_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_store',
            name='user',
        ),
        migrations.AddField(
            model_name='seller_store',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
