# Generated by Django 4.2.1 on 2023-06-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_remove_seller_store_user_seller_store_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_store',
            old_name='store_Name',
            new_name='store_name',
        ),
    ]
