# Generated by Django 4.2.1 on 2023-06-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_seller_store_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Payment Pending', 'Payment Pending'), ('Payment Done', 'Payment Done')], default='Payment Pending', max_length=200),
        ),
    ]
