# Generated by Django 4.2.1 on 2023-06-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
