# Generated by Django 4.2.1 on 2023-06-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_product_seller_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller_company',
            new_name='Seller_store',
        ),
    ]
