# Generated by Django 4.2.1 on 2023-06-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0008_rename_seller_company_seller_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_company',
            new_name='seller_store',
        ),
        migrations.RenameField(
            model_name='seller_store',
            old_name='company_Name',
            new_name='store_Name',
        ),
        migrations.AddField(
            model_name='seller_store',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
